language: php
php:
- '7.0'
- '7.1'
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS vucket;'
- mysql -e 'CREATE TABLE `vucket`.`accounts` (`id` int(11) NOT NULL AUTO_INCREMENT, `username` varchar(1000)
  NOT NULL, `email` varchar(1000) NOT NULL, `password` varchar(255) NOT NULL, `frozen`
  int(1) NOT NULL, `2fa` int(1) NOT NULL, `secret` varchar(100) NOT NULL, `logtag`
  varchar(100) NOT NULL, `tokentag` varchar(100) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`functions` (`id` int(11) NOT NULL AUTO_INCREMENT, `time` bigint(100)
  NOT NULL, `state` varchar(15) NOT NULL, `func` varchar(1000) NOT NULL, `logid` int(11)
  NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`log` (`id` int(11) NOT NULL AUTO_INCREMENT, `code` varchar(100)
  NOT NULL, `trace` varchar(5000) NOT NULL, `mysql` text NOT NULL, `ip` varchar(45)
  NOT NULL, `time` bigint(100) NOT NULL, `type` varchar(100) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB
  DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`tokens` (`id` int(11) NOT NULL AUTO_INCREMENT, `tokentag` varchar(100)
  NOT NULL, `token` varchar(50) NOT NULL, `activation` bigint(100) NOT NULL, `expiration`
  bigint(100) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`vat` (`id` int(11) NOT NULL AUTO_INCREMENT, `userid` int(11) NOT NULL, `app` varchar(100) NOT NULL, 
  `ring` int(1) NOT NULL, PRIMARY KEY (`id`)) Engine=InnoDB DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`services` (`id` int(11) NOT NULL AUTO_INCREMENT, `type` int(3) NOT NULL, `name` varchar(1000) NOT NULL, `price` int(5) NOT NULL, PRIMARY KEY (`id`)) Engine=InnoDB DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`invoices` (`id` int(11) NOT NULL AUTO_INCREMENT, `type` int(3) NOT NULL, `userid` int(11) NOT NULL, `due` int(5) NOT NULL, `credits` int(5) NOT NULL, `generated` bigint(100) NOT NULL, `dueby` bigint(100) NOT NULL, `status` int(1) NOT NULL, PRIMARY KEY (`id`)) Engine=InnoDB DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`cycles` (`id` int(11) NOT NULL AUTO_INCREMENT, `type` int(3) NOT NULL, `userid` int(11) NOT NULL, `dayofmo` int(2) NOT NULL, PRIMARY KEY (`id`)) Engine=InnoDB DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`vat_versions` (`id` int(11) NOT NULL AUTO_INCREMENT, `app` varchar(100) NOT NULL, `version` varchar(100) NOT NULL, `ring` int(1) NOT NULL, PRIMARY KEY (`id`)) Engine=InnoDB DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`install_data` (`id` int(11) NOT NULL AUTO_INCREMENT, `time` bigint(100) NOT NULL, `app` varchar(100) NOT NULL, `version` varchar(100) NOT NULL, PRIMARY KEY (`id`)) Engine=InnoDB DEFAULT CHARSET=latin1;'
- mysql -e 'CREATE TABLE `vucket`.`health_cache` (`id` int(11) NOT NULL AUTO_INCREMENT, `created` bigint(100) NOT NULL, `timeframe` int(11) NOT NULL, `success` bigint(100) NOT NULL, `degraded` bigint(100) NOT NULL, `error` bigint(100) NOT NULL, PRIMARY KEY (`id`)) Engine=InnoDB DEFAULT CHARSET=latin1;'
script: phpunit test.php
