language: php
php:
  - '7.0'
  - '7.1'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS vucket;'
  - mysql -e 'CREATE TABLE `vucket`.`accounts` (`id` int(11) NOT NULL, `username` varchar(1000) NOT NULL, `email` varchar(1000) NOT NULL, `password` varchar(255) NOT NULL, `frozen` int(1) NOT NULL, `2fa` int(1) NOT NULL, `secret` varchar(100) NOT NULL, `logtag` varchar(100) NOT NULL, `tokentag` varchar(100) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;'
  - mysql -e 'CREATE TABLE `vucket`.`functions` (`id` int(11) NOT NULL, `time` bigint(100) NOT NULL, `state` varchar(15) NOT NULL, `func` varchar(1000) NOT NULL, `logid` int(11) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;'
  - mysql -e 'CREATE TABLE `vucket`.`log` (`id` int(11) NOT NULL, `code` varchar(100) NOT NULL, `trace` varchar(5000) NOT NULL, `mysql` text NOT NULL, `ip` varchar(45) NOT NULL, `time` bigint(100) NOT NULL, `type` varchar(100) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;'
  - mysql -e 'CREATE TABLE `vucket`.`tokens` (`id` int(11) NOT NULL, `tokentag` varchar(100) NOT NULL, `token` varchar(50) NOT NULL, `activation` bigint(100) NOT NULL, `expiration` bigint(100) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;'
  - touch secrets.php
script: phpunit tests.php
